Fix need of OpenAI API key if using Litellm
TheR1D/shell_gpt pull request #621
Opened 2024-08-30 05:44 UTC by abhishekbhakat

Fixes the need of unused OpenAI API key if Litellm is configured after #604.

2024-10-15 20:43 UTC, code-cntrl requested changes

2024-10-15 20:43 UTC, code-cntrl commented on .gitignore
Is this intended to be included in this pull request?

2024-10-16 09:37 UTC, abhishekbhakat commented on .gitignore
The project should have a gitignore. I found it helpful in development, so I kept it. Any specific reason you'd not want the gitignore?

2024-12-06 06:24 UTC, abhishekbhakat commented
@code-cntrl dropped the .gitignore
See if you can merge this.

I want the PR #575 to close but having to say you have to set a dummy key for `OPENAI_API_KEY` to use anything from LiteLLm makes it a friction.

2024-12-06 17:05 UTC, lucasliet commented
subject of the issue https://github.com/TheR1D/shell_gpt/issues/651

2024-12-06 17:45 UTC, lucasliet commented
in the case of #575, how can I provide the api_key from gemini in this implementation?

it would be good to have usage example on readme

2024-12-06 18:36 UTC, abhishekbhakat commented
@lucasliet you need to set `GEMINI_API_KEY` as env variable. As per https://docs.litellm.ai/docs/providers/gemini.

I explained in https://github.com/TheR1D/shell_gpt/pull/604#issuecomment-2259749221

2025-05-25 13:30 UTC, closed without merging